Homework3
made-ml-in-prod-2021/birlikov pull request #4
Opened 2021-06-09 05:11 UTC by birlikov

Что сделано:
0) Поднимите airflow локально, используя docker compose - DONE

1) (5 баллов) Реализуйте dag, который генерирует данные для обучения модели - DONE

2) (10 баллов) Реализуйте dag, который обучает модель еженедельно, используя данные за текущий день - DONE

3) Реализуйте dag, который использует модель ежедневно (5 баллов) - DONE

4) все даги реализованы только с помощью DockerOperator (10 баллов) - DONE

9) традиционно, самооценка (1 балл) - DONE

Моя оценка: 31 балл

Скриншоты удачных запусков приложены в README.

2021-06-09 07:16 UTC, Mikhail-M requested changes
pyche пожалуйста удалите

2021-06-09 15:51 UTC, MikhailYeka commented
Посмотрел, работа хорошая, согласен с самооценкой

2021-06-09 15:51 UTC, MikhailYeka approved these changes

2021-06-17 08:01 UTC, Mikhail-M requested changes
удалить .pyc 😡😡😡😡😡😡

2021-06-17 08:51 UTC, birlikov commented
> удалить .pyc 😡😡😡😡😡😡

Извиняюсь, не заметил, вроде теперь все .рус файлы удалил.

2021-06-18 07:25 UTC, Mikhail-M commented on airflow_ml_dags/dags/3_dag_predict.py
> +    model_path = Variable.get("model_path")
https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html#variables FYI

2021-06-18 07:26 UTC, Mikhail-M approved these changes
Баллы: 29
-2 балла за наличие .pyc из другой ДЗ в реквесте

2021-06-18 08:02 UTC, merged